version: "3"
services:
  # app:
  #   build: .
  #   ports:
  #     - "3000:3000"
  #   environment:
  #     - DATABASE_URL=postgres://postgres:${POSTGRES_PASSWORD}@db:5432/postgres
  #   depends_on:
  #     - db
  db:
    image: postgres:16
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
